# Generated by Django 3.0.3 on 2020-03-11 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MsgContent',
            fields=[
                ('msgId', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=500)),
                ('postTime', models.DateTimeField(auto_now_add=True)),
                ('readStatus', models.BooleanField(default=False)),
                ('ruid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.signup')),
                ('suid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senderuid', to='signup.signup')),
            ],
            options={
                'db_table': 'messaging',
            },
        ),
    ]
