# Generated by Django 3.0.3 on 2020-03-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('pnumber', models.IntegerField()),
                ('location', models.CharField(default='Nairobi/Kenya', max_length=30)),
                ('hobby', models.CharField(max_length=30)),
                ('profilepic', models.FileField(upload_to='')),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'signup',
            },
        ),
    ]
