# Generated by Django 3.0.6 on 2020-06-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
