# Generated by Django 3.0.6 on 2020-06-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20200601_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='location',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='profilepic',
            field=models.ImageField(upload_to=''),
        ),
    ]
