# Generated by Django 3.0.3 on 2020-03-11 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=50)),
                ('event_description', models.TextField(max_length=500)),
                ('post_time', models.TimeField(auto_now_add=True)),
                ('event_brief_pic', models.FileField(upload_to='')),
                ('usereventid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='signup.signup')),
            ],
            options={
                'db_table': 'events',
            },
        ),
    ]
