# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-12 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_description',
            field=models.TextField(max_length=200),
        ),
    ]
