# Generated by Django 3.0.3 on 2020-03-11 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='group_id',
        ),
    ]
