# Generated by Django 3.0.3 on 2020-03-11 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_remove_members_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='group_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='groups.Groups'),
            preserve_default=False,
        ),
    ]
