# Generated by Django 3.0.3 on 2020-03-11 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_members_group_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groups',
            old_name='group_id',
            new_name='id',
        ),
    ]
