# Generated by Django 3.0.3 on 2020-03-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
        ('groups', '0005_groups_group_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='group_admin',
        ),
        migrations.AddField(
            model_name='groups',
            name='group_admin',
            field=models.ManyToManyField(to='signup.signup'),
        ),
    ]
