# Generated by Django 3.0.3 on 2020-03-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
        ('groups', '0006_auto_20200312_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='group_admin',
            field=models.ManyToManyField(related_name='signup', to='signup.signup'),
        ),
    ]
