# Generated by Django 3.0.6 on 2020-06-06 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_auto_20200602_0538'),
        ('groups', '0009_groups_group_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_content',
            fields=[
                ('postuid', models.AutoField(primary_key=True, serialize=False)),
                ('post_content', models.CharField(max_length=1024)),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('group_post_own', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_group_own', to='groups.Groups')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_content_bridge', to='signup.signup')),
            ],
            options={
                'db_table': 'group_content',
            },
        ),
    ]
