# Generated by Django 3.0.3 on 2020-03-13 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
        ('discover', '0002_auto_20200313_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='user_following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followinghello', to='signup.signup'),
        ),
    ]
