# Generated by Django 3.0.3 on 2020-03-13 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
        ('discover', '0003_auto_20200313_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='user_follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followercounter', to='signup.signup'),
        ),
        migrations.AlterField(
            model_name='followers',
            name='user_following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followingcounter', to='signup.signup'),
        ),
    ]
